<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <InternalsVisibleTo Include="Njord.Enrichment.Tests" />
        <InternalsVisibleTo Include="Njord.Mqtt.Tests" />
        <InternalsVisibleTo Include="Njord.Tests" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Njord.Core\Njord.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Akka.Cluster.Hosting" />
      <PackageReference Include="MQTTnet" />
      <PackageReference Include="Servus.Akka" />
    </ItemGroup>

</Project>
