# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from njord.v2 import admin_pb2 as njord_dot_v2_dot_admin__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in njord/v2/admin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AdminServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetConfig = channel.unary_unary(
                '/njord.v2.AdminService/GetConfig',
                request_serializer=njord_dot_v2_dot_admin__pb2.GetConfigRequest.SerializeToString,
                response_deserializer=njord_dot_v2_dot_admin__pb2.NjordConfig.FromString,
                _registered_method=True)
        self.StreamConfig = channel.unary_stream(
                '/njord.v2.AdminService/StreamConfig',
                request_serializer=njord_dot_v2_dot_admin__pb2.StreamConfigRequest.SerializeToString,
                response_deserializer=njord_dot_v2_dot_admin__pb2.NjordConfig.FromString,
                _registered_method=True)
        self.SetLocations = channel.unary_unary(
                '/njord.v2.AdminService/SetLocations',
                request_serializer=njord_dot_v2_dot_admin__pb2.SetLocationsRequest.SerializeToString,
                response_deserializer=njord_dot_v2_dot_admin__pb2.ConfigResponse.FromString,
                _registered_method=True)
        self.SetSettings = channel.unary_unary(
                '/njord.v2.AdminService/SetSettings',
                request_serializer=njord_dot_v2_dot_admin__pb2.SetSettingsRequest.SerializeToString,
                response_deserializer=njord_dot_v2_dot_admin__pb2.ConfigResponse.FromString,
                _registered_method=True)
        self.SetEnrichment = channel.unary_unary(
                '/njord.v2.AdminService/SetEnrichment',
                request_serializer=njord_dot_v2_dot_admin__pb2.SetEnrichmentRequest.SerializeToString,
                response_deserializer=njord_dot_v2_dot_admin__pb2.ConfigResponse.FromString,
                _registered_method=True)
        self.SetBudget = channel.unary_unary(
                '/njord.v2.AdminService/SetBudget',
                request_serializer=njord_dot_v2_dot_admin__pb2.SetBudgetRequest.SerializeToString,
                response_deserializer=njord_dot_v2_dot_admin__pb2.ConfigResponse.FromString,
                _registered_method=True)


class AdminServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLocations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSettings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetEnrichment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetBudget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=njord_dot_v2_dot_admin__pb2.GetConfigRequest.FromString,
                    response_serializer=njord_dot_v2_dot_admin__pb2.NjordConfig.SerializeToString,
            ),
            'StreamConfig': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamConfig,
                    request_deserializer=njord_dot_v2_dot_admin__pb2.StreamConfigRequest.FromString,
                    response_serializer=njord_dot_v2_dot_admin__pb2.NjordConfig.SerializeToString,
            ),
            'SetLocations': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLocations,
                    request_deserializer=njord_dot_v2_dot_admin__pb2.SetLocationsRequest.FromString,
                    response_serializer=njord_dot_v2_dot_admin__pb2.ConfigResponse.SerializeToString,
            ),
            'SetSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSettings,
                    request_deserializer=njord_dot_v2_dot_admin__pb2.SetSettingsRequest.FromString,
                    response_serializer=njord_dot_v2_dot_admin__pb2.ConfigResponse.SerializeToString,
            ),
            'SetEnrichment': grpc.unary_unary_rpc_method_handler(
                    servicer.SetEnrichment,
                    request_deserializer=njord_dot_v2_dot_admin__pb2.SetEnrichmentRequest.FromString,
                    response_serializer=njord_dot_v2_dot_admin__pb2.ConfigResponse.SerializeToString,
            ),
            'SetBudget': grpc.unary_unary_rpc_method_handler(
                    servicer.SetBudget,
                    request_deserializer=njord_dot_v2_dot_admin__pb2.SetBudgetRequest.FromString,
                    response_serializer=njord_dot_v2_dot_admin__pb2.ConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'njord.v2.AdminService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('njord.v2.AdminService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdminService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/njord.v2.AdminService/GetConfig',
            njord_dot_v2_dot_admin__pb2.GetConfigRequest.SerializeToString,
            njord_dot_v2_dot_admin__pb2.NjordConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/njord.v2.AdminService/StreamConfig',
            njord_dot_v2_dot_admin__pb2.StreamConfigRequest.SerializeToString,
            njord_dot_v2_dot_admin__pb2.NjordConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetLocations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/njord.v2.AdminService/SetLocations',
            njord_dot_v2_dot_admin__pb2.SetLocationsRequest.SerializeToString,
            njord_dot_v2_dot_admin__pb2.ConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/njord.v2.AdminService/SetSettings',
            njord_dot_v2_dot_admin__pb2.SetSettingsRequest.SerializeToString,
            njord_dot_v2_dot_admin__pb2.ConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetEnrichment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/njord.v2.AdminService/SetEnrichment',
            njord_dot_v2_dot_admin__pb2.SetEnrichmentRequest.SerializeToString,
            njord_dot_v2_dot_admin__pb2.ConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetBudget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/njord.v2.AdminService/SetBudget',
            njord_dot_v2_dot_admin__pb2.SetBudgetRequest.SerializeToString,
            njord_dot_v2_dot_admin__pb2.ConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
