# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from njord.v2 import sensor_pb2 as njord_dot_v2_dot_sensor__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in njord/v2/sensor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SensorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Push = channel.unary_unary(
                '/njord.v2.SensorService/Push',
                request_serializer=njord_dot_v2_dot_sensor__pb2.SensorReading.SerializeToString,
                response_deserializer=njord_dot_v2_dot_sensor__pb2.PushResponse.FromString,
                _registered_method=True)
        self.StreamPush = channel.stream_unary(
                '/njord.v2.SensorService/StreamPush',
                request_serializer=njord_dot_v2_dot_sensor__pb2.SensorReading.SerializeToString,
                response_deserializer=njord_dot_v2_dot_sensor__pb2.PushResponse.FromString,
                _registered_method=True)


class SensorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Push(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPush(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SensorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Push': grpc.unary_unary_rpc_method_handler(
                    servicer.Push,
                    request_deserializer=njord_dot_v2_dot_sensor__pb2.SensorReading.FromString,
                    response_serializer=njord_dot_v2_dot_sensor__pb2.PushResponse.SerializeToString,
            ),
            'StreamPush': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamPush,
                    request_deserializer=njord_dot_v2_dot_sensor__pb2.SensorReading.FromString,
                    response_serializer=njord_dot_v2_dot_sensor__pb2.PushResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'njord.v2.SensorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('njord.v2.SensorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SensorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Push(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/njord.v2.SensorService/Push',
            njord_dot_v2_dot_sensor__pb2.SensorReading.SerializeToString,
            njord_dot_v2_dot_sensor__pb2.PushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPush(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/njord.v2.SensorService/StreamPush',
            njord_dot_v2_dot_sensor__pb2.SensorReading.SerializeToString,
            njord_dot_v2_dot_sensor__pb2.PushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
