# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: njord/v2/sensor.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'njord/v2/sensor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15njord/v2/sensor.proto\x12\x08njord.v2\x1a\x1fgoogle/protobuf/timestamp.proto\"\x95\x01\n\rSensorReading\x12\"\n\x04kind\x18\x01 \x01(\x0e\x32\x14.njord.v2.SensorKind\x12\x10\n\x08location\x18\x02 \x01(\t\x12\x0e\n\x06source\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\x01\x12/\n\x0bmeasured_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\":\n\x0cPushResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x18\n\x10rejection_reason\x18\x02 \x01(\t*n\n\nSensorKind\x12\x1b\n\x17SENSOR_KIND_UNSPECIFIED\x10\x00\x12\"\n\x1eSENSOR_KIND_INDOOR_TEMPERATURE\x10\x01\x12\x1f\n\x1bSENSOR_KIND_INDOOR_HUMIDITY\x10\x02\x32\x89\x01\n\rSensorService\x12\x37\n\x04Push\x12\x17.njord.v2.SensorReading\x1a\x16.njord.v2.PushResponse\x12?\n\nStreamPush\x12\x17.njord.v2.SensorReading\x1a\x16.njord.v2.PushResponse(\x01\x42\x10\xaa\x02\rNjord.Grpc.V2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'njord.v2.sensor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\rNjord.Grpc.V2'
  _globals['_SENSORKIND']._serialized_start=280
  _globals['_SENSORKIND']._serialized_end=390
  _globals['_SENSORREADING']._serialized_start=69
  _globals['_SENSORREADING']._serialized_end=218
  _globals['_PUSHRESPONSE']._serialized_start=220
  _globals['_PUSHRESPONSE']._serialized_end=278
  _globals['_SENSORSERVICE']._serialized_start=393
  _globals['_SENSORSERVICE']._serialized_end=530
# @@protoc_insertion_point(module_scope)
