# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from njord.v2 import weather_pb2 as njord_dot_v2_dot_weather__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in njord/v2/weather_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WeatherServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCatalog = channel.unary_unary(
                '/njord.v2.WeatherService/GetCatalog',
                request_serializer=njord_dot_v2_dot_weather__pb2.GetCatalogRequest.SerializeToString,
                response_deserializer=njord_dot_v2_dot_weather__pb2.GetCatalogResponse.FromString,
                _registered_method=True)
        self.GetForecast = channel.unary_unary(
                '/njord.v2.WeatherService/GetForecast',
                request_serializer=njord_dot_v2_dot_weather__pb2.GetForecastRequest.SerializeToString,
                response_deserializer=njord_dot_v2_dot_weather__pb2.GetForecastResponse.FromString,
                _registered_method=True)
        self.GetEnrichments = channel.unary_unary(
                '/njord.v2.WeatherService/GetEnrichments',
                request_serializer=njord_dot_v2_dot_weather__pb2.GetEnrichmentsRequest.SerializeToString,
                response_deserializer=njord_dot_v2_dot_weather__pb2.GetEnrichmentsResponse.FromString,
                _registered_method=True)
        self.StreamForecasts = channel.unary_stream(
                '/njord.v2.WeatherService/StreamForecasts',
                request_serializer=njord_dot_v2_dot_weather__pb2.StreamForecastsRequest.SerializeToString,
                response_deserializer=njord_dot_v2_dot_weather__pb2.ForecastUpdate.FromString,
                _registered_method=True)
        self.StreamEnrichments = channel.unary_stream(
                '/njord.v2.WeatherService/StreamEnrichments',
                request_serializer=njord_dot_v2_dot_weather__pb2.StreamEnrichmentsRequest.SerializeToString,
                response_deserializer=njord_dot_v2_dot_weather__pb2.EnrichmentEvent.FromString,
                _registered_method=True)


class WeatherServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCatalog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetForecast(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEnrichments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamForecasts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEnrichments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WeatherServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCatalog': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCatalog,
                    request_deserializer=njord_dot_v2_dot_weather__pb2.GetCatalogRequest.FromString,
                    response_serializer=njord_dot_v2_dot_weather__pb2.GetCatalogResponse.SerializeToString,
            ),
            'GetForecast': grpc.unary_unary_rpc_method_handler(
                    servicer.GetForecast,
                    request_deserializer=njord_dot_v2_dot_weather__pb2.GetForecastRequest.FromString,
                    response_serializer=njord_dot_v2_dot_weather__pb2.GetForecastResponse.SerializeToString,
            ),
            'GetEnrichments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnrichments,
                    request_deserializer=njord_dot_v2_dot_weather__pb2.GetEnrichmentsRequest.FromString,
                    response_serializer=njord_dot_v2_dot_weather__pb2.GetEnrichmentsResponse.SerializeToString,
            ),
            'StreamForecasts': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamForecasts,
                    request_deserializer=njord_dot_v2_dot_weather__pb2.StreamForecastsRequest.FromString,
                    response_serializer=njord_dot_v2_dot_weather__pb2.ForecastUpdate.SerializeToString,
            ),
            'StreamEnrichments': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEnrichments,
                    request_deserializer=njord_dot_v2_dot_weather__pb2.StreamEnrichmentsRequest.FromString,
                    response_serializer=njord_dot_v2_dot_weather__pb2.EnrichmentEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'njord.v2.WeatherService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('njord.v2.WeatherService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WeatherService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCatalog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/njord.v2.WeatherService/GetCatalog',
            njord_dot_v2_dot_weather__pb2.GetCatalogRequest.SerializeToString,
            njord_dot_v2_dot_weather__pb2.GetCatalogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetForecast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/njord.v2.WeatherService/GetForecast',
            njord_dot_v2_dot_weather__pb2.GetForecastRequest.SerializeToString,
            njord_dot_v2_dot_weather__pb2.GetForecastResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEnrichments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/njord.v2.WeatherService/GetEnrichments',
            njord_dot_v2_dot_weather__pb2.GetEnrichmentsRequest.SerializeToString,
            njord_dot_v2_dot_weather__pb2.GetEnrichmentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamForecasts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/njord.v2.WeatherService/StreamForecasts',
            njord_dot_v2_dot_weather__pb2.StreamForecastsRequest.SerializeToString,
            njord_dot_v2_dot_weather__pb2.ForecastUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEnrichments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/njord.v2.WeatherService/StreamEnrichments',
            njord_dot_v2_dot_weather__pb2.StreamEnrichmentsRequest.SerializeToString,
            njord_dot_v2_dot_weather__pb2.EnrichmentEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
