<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <ServerGarbageCollection>false</ServerGarbageCollection>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Njord.Tests" />
        <InternalsVisibleTo Include="Njord.IntegrationTests" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Akka.Cluster.Hosting" />
      <PackageReference Include="Akka.Hosting" />
      <PackageReference Include="Akka.Logger.Serilog" />
      <PackageReference Include="Akka.Remote.Hosting" />
      <PackageReference Include="prometheus-net.AspNetCore" />
      <PackageReference Include="Serilog" />
      <PackageReference Include="Serilog.Enrichers.Environment" />
      <PackageReference Include="Serilog.Enrichers.Thread" />
      <PackageReference Include="Serilog.Extensions.Hosting" />
      <PackageReference Include="Serilog.Settings.Configuration" />
      <PackageReference Include="Serilog.Sinks.Console" />
      <PackageReference Include="Microsoft.Data.Sqlite" />
      <PackageReference Include="Npgsql" />
      <PackageReference Include="Servus" />
      <PackageReference Include="Servus.Akka" />
      <PackageReference Include="Akka.Persistence.Sql.Hosting" />
      <PackageReference Include="Akka.Streams" />
    </ItemGroup>

<ItemGroup>
  <ProjectReference Include="..\Njord.Domain\Njord.Domain.csproj" />
  <ProjectReference Include="..\Njord.Persistence\Njord.Persistence.csproj" />
  <ProjectReference Include="..\Njord.Messages\Njord.Messages.csproj" />
  <ProjectReference Include="..\Njord.Core\Njord.Core.csproj" />
  <ProjectReference Include="..\Njord.Sensors\Njord.Sensors.csproj" />
  <ProjectReference Include="..\Njord.Ingest\Njord.Ingest.csproj" />
  <ProjectReference Include="..\Njord.Grpc\Njord.Grpc.csproj" />
  <ProjectReference Include="..\Njord.Pipeline\Njord.Pipeline.csproj" />
  <ProjectReference Include="..\Njord.Egress\Njord.Egress.csproj" />
  <ProjectReference Include="..\Njord.Mqtt\Njord.Mqtt.csproj" />
  <ProjectReference Include="..\Njord.Enrichment\Njord.Enrichment.csproj" />
</ItemGroup>

</Project>
