using System.Linq;
using ArchUnitNET.Domain;
using ArchUnitNET.xUnitV3;
using Xunit;
using static ArchUnitNET.Fluent.ArchRuleDefinition;

namespace Njord.Tests.Architecture;

public sealed class ConventionArchitectureSpec
{
    // See ZoneArchitectureSpec: the shared architecture load exceeds the default 5 s timeout.
    private const int ArchitectureTimeoutMs = 60_000;

    private static readonly string[] _testAttributes = ["Xunit.FactAttribute", "Xunit.TheoryAttribute"];

    private static bool DeclaresTests(Class c)
        => c.Members.OfType<MethodMember>().Any(m => m.Attributes.Any(a => _testAttributes.Contains(a.FullName)));

    [Fact(Timeout = ArchitectureTimeoutMs)]
    public void Production_classes_are_sealed()
    {
        Classes().That().Are(NjordArchitecture.ProductionTypes)
            .And().AreNotAbstract()
            .And().DoNotHaveName("Program") // compiler-generated by top-level statements in Program.cs; cannot be sealed
            .Should().BeSealed()
            .Check(NjordArchitecture.Instance);
    }

    [Fact(Timeout = ArchitectureTimeoutMs)]
    public void Test_classes_with_tests_are_sealed_and_suffixed_Spec()
    {
        Classes().That().Are(NjordArchitecture.TestTypes)
            .And().FollowCustomPredicate(DeclaresTests, "declare tests")
            .Should().BeSealed()
            .AndShould().HaveNameEndingWith("Spec")
            .Check(NjordArchitecture.Instance);
    }
}
