<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <InternalsVisibleTo Include="Njord.Core.Tests" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Njord.Domain\Njord.Domain.csproj" />
        <ProjectReference Include="..\Njord.Messages\Njord.Messages.csproj" />
        <ProjectReference Include="..\Njord.Persistence\Njord.Persistence.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
      <PackageReference Include="Microsoft.Extensions.Options" />
      <PackageReference Include="Newtonsoft.Json" />
    </ItemGroup>

</Project>
