name: CI

on:
  pull_request:
    paths-ignore:
      - 'docs/**'

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: st0o0/github-workflows/.github/workflows/dotnet-ci.yml@main
    with:
      solution-file: Njord.slnx

  commitlint:
    uses: st0o0/github-workflows/.github/workflows/commitlint.yml@main
