name: Docs

on:
  release:
    types: [published]

concurrency:
  group: docs
  cancel-in-progress: false

jobs:
  deploy:
    uses: st0o0/github-workflows/.github/workflows/docs.yml@main
    with:
      needs-dotnet-build: true
      dotnet-project-path: src
    permissions:
      contents: read
      pages: write
      id-token: write
